---
# ©Copyright 2015 Hewlett-Packard Development Company, L.P.

vertica_catalog_dir: /var/vertica/catalog
vertica_data_dir: /var/vertica/data
vertica_ips: 127.0.0.1
skip_install: false
run_mode: Install
vertica_env: {LC_ALL: en_US.UTF-8, LANG: en_US.UTF-8}
vertica_database_name: vertica_test_db
vertica_client_port: 5433
monasca_wait_for_period: 90
vertica_script_location: /opt/monasca
vertica_use_apt: false
vertica_license: CE
vertica_version: 9.0.1
vertica_package: vertica_9.0.1-0_amd64.deb
